# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningLogs', '0004_entry_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default=12),
            preserve_default=False,
        ),
    ]
